name: Build

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure gradle
        run: ./gradlew

      - name: Build plugin
        run: ./gradlew jar

      - name: Upload plugin jar
        uses: actions/upload-artifact@v3
        with:
          name: DnsCheck
          path: build/libs/DnsCheck*.jar
